title: "TnyavnTo - Blog"
author: "TnyavnTo"
description: "This is my Official Blog. You'll see me write here about various things."
email: "sna.organics@gmail.com"
#witter_username: "sna_organics"
github_username: "svxy"
#linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
instagram_username: itssvxy
#pinterest_username: username
#youtube_username: "@Gen_Z_Grease_Monkey"
#googleplus_username: +username

theme: "minima"

google_analytics: "G-9GBPH0SH3R"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      tags: Other
